- views/parties.erb
- views/people.erb
- views/terms.erb
On the ‘parties’ and ‘terms’ pages, if we have nothing to show, give examples of how to structure your data.
(If we have no People, then there’s a much bigger problem!)
We still need to add the /help page that these link to (#14), and to style the <pre> sections better.
Closes #13
> Add basic explanation of data formats inplace

- views/person.erb
if a Membership contains an area, show it.
Before:
After:
Closes #26
> Display Area if it exists

- t/web/eduskunta.rb
- views/term.erb
On the term page, only show dates for a membership if those differ from the dates of the term.
Fixes #34
> Only show dates for memberships if they don't match the term.

- app.rb
Sinatra has built-in magic `__sinatra__` routes, for things like
images. We need to allow those to pass through our before filter.
Before:
After:
Fixes #52 
I couldn't work out how to test this, as the text runs in test mode, rather than development, which doesn't have the same behaviour, and I couldn't find a way to override that just for a single test. Opening that as #56
> Pass `__sinatra__` requests through

- app.rb
- lib/popolo_helper.rb
- t/helpers/wales.rb
- t/web/wales.rb
- views/person.erb
A Person page is breaking when viewing someone who’s in both the Legislature and the Executive
As we’re not really handling Executive positions at all yet, make this display only legislative memberships for now.
Before:
After:
Fixes #51
> Only show legislative memberships on a Person page

- t/web/eduskunta.rb
- views/term.erb
As a step towards #60, simply group by Person, and combine their memberships where relevant. 
Where the dates actually combine to span the entire Term, we shouldn't actually show them, but Release Early, Release Often...
Before:
After:
> Only show each person once on the Term page

- lib/popolo_helper.rb
- t/web/greenland.rb
If there’s no start/end date on a Membership, or the Legislative
Period, sorting fails (as it can’t compare Promises)
Before: 
After:
Fixes #65
> 65/ Fix Greenland Person pages

- app.rb
- t/web/greenland.rb
- views/person.erb
Add the relevant Term information to the list of legislative memberships on the Person page.
Before: 
After:
Closes #58
> 58/ Show Terms on Person page

- app.rb
- lib/popolo_helper.rb
- t/helpers/eduskunta.rb
- t/web/greenland.rb
Allow /person/name as well as /person/id
This will only work for an exact match on name, and doesn’t handle
multiple people having the same name.
> 69: /person/name

- app.rb
- lib/popolo_helper.rb
- t/helpers/eduskunta.rb
- t/web/eduskunta-old.rb
- t/web/eduskunta.rb
on the Terms page, only provide links to Terms that actually have
members.
Before:
After:
Closes #74
> 74/ Empty terms

- data/wales.json
- data/wales/Rakefile.rb
- data/wales/popit.json
- data/wales/wales.json
Add a ‘current’ term as a data-processing step. We’ll extract this to something reusable when we need to do more.
Closes #28
> 28/ Add default term for Wales

- app.rb
- t/web/greenland.rb
When introducing the ‘find by name’ I got ruby’s truthiness test wrong (an empty list is `true`, not `false`). Move the check to the right place, and add a regression test.
> Test for no such person

- t/web/eduskunta.rb
- views/party.erb
- views/term.erb
- On the Party page show how many Seats they’ve had in each Term
before:
after:
- On the Term page, link to the Party page
before:
after:
Closes #22
> Tie Terms and Parties better

- app.rb
- t/web/term_table.rb
- views/term_table.erb
For each country, have a simple table that shows the legislature during that term. This can be accessed by id, or simply visiting `/country/term_table` will default to the current term.
Party changes, etc, are simply shown as grouped rows:
> Add a basic term_table page

- app.rb
- lib/popolo_helper.rb
- t/web/term_table.rb
- views/term_table.erb
Allow navigation backwards and forwards on Term Table pages. (Closes #101)
Also make the `current_term` call a little more robust (closes #104)
> Term Navigation

- app.rb
- data/australia.json
- data/australia/Rakefile.rb
- data/australia/processed.json
- lib/popolo_helper.rb
- t/web/term_table.rb
We don’t do a very good job of it yet, in that the memberships of both houses are intermixed, but it’s better than showing nothing, as at least we could group by it in the templates.
> Handle bicameral parliaments

- views/term_table.erb
Add a count of how many seats each party group had during this Term.
It’s not ideal, as it simply counts the number of Memberships over the
Term, but it’s a good first step, and lets us style the page better
whilst we work out what the correct calculations should be.
Closes #98 (#111 will be the more advanced version)
> Add basic Party Groupings box

- data/australia.json
- data/australia/Rakefile.rb
- data/australia/processed.json
- t/web/term_table.rb
- views/term_table.erb
Show a separate table for each House, where appropriate:
Closes #97 
The party groupings at the top are still a combination of both. It’ll be easy to split those similarly, but it might be useful in some cases to view the totals as well. Needs a little more thought as to the best way to show that… #113
> Split Term Table for bicameral legislatures

- public/javascript/main.js
- t/web/term_table.rb
- views/layout.erb
- views/sass/_components.scss
- views/sass/_custom.scss
- views/sass/main.scss
- views/styling.erb
- views/term_table.erb
Part of #96.
Includes visual distinction between parties and members, buttons to jump between bicameral chambers and fixed table headers when you scroll down the list of members.
> Improve layout of "Term Table" page

- app.rb
- t/web/eduskunta.rb
Rather than maintaining a list of country/filename mappings, simply enable a new country just by dropping it in the `data` directory.
Now that the data is all generated in a different repo, this is much cleaner and simpler (and means that  simple data-drop PRs from `everypolitician-data` will be automatically tested by Travis without needing a separate change to add the configuration line)
This removes the ability to have multiple URLs to a country, but that’s not really a necessary feature, and if we want we can bring it back later in a different way. We also need to remove South Africa, but that's a good thing, as it's not ready yet.
> Remove need for file/country mapping

- app.rb
- lib/popolo_helper.rb
- views/term_table.erb
Only display a dates column when at least one Membership has start or
end dates different from the Term itself
> Remove empty dates column

- views/sass/_mixins.scss
Add css rule to fix flexbox wrapping in Safari (thanks @dracos)
Fixes #127
Before:
After:
> Add webkit-flex-wrap for Safari

- t/web/term_table.rb
- views/term_table.erb
Sorting only by the number of seats they have leads to inconsistent
returns (and thus needless HTML changes to eyeball in diffs). If
membership numbers are the same, order by name.
> Fix the sort-order of Parties

- lib/popolo_helper.rb
- t/data/term_table.rb
The CSV output for a term now includes a column containing the chamber.
Fixes #145
> Include 'chamber' column in CSV output

- public/javascript/main.js
- views/layout.erb
- views/sass/_components.scss
- views/term_table.erb
Looks like this for countries with more than one term:
Stacks vertically on narrow screens:
> Add select box for quickly jumping between terms

- views/layout.erb
Getting jQuery and Google Fonts over http means that they don't work if
we're viewing the site over https (e.g. on heroku). Switch to always
using the https: versions.
> Use https for everything

- scripts/release.sh
We're cloning the viewer-static repository, so we need to cd into that repository as well.
> Fix release.sh to cd into correct directory

- views/layout.erb
- views/sass/_site-header.scss
Now that we have Country pages, clicking on the country name in the
header of Term pages should go to them. Closes #231
> Make the Country name in the header a link

- app.rb
Only offer links / jumps to terms that actually had members (just like
on the front page for the country).
Closes #254
> Don't show old terms on Term Table page

- app.rb
- lib/popolo_helper.rb
- t/web/term_table/australia.rb
- t/web/term_table/canada.rb
- t/web/term_table/finland.rb
- t/web/term_table/malaysia.rb
- t/web/term_table/nz.rb
As part of the move to handling multiple legislatures per country (#291) add the house name into the URL.
For now we still don’t cope properly with more than one house per country, but this gets us closer to that.
> Add the house name to term-table URLs

- app.rb
- views/term_table.erb
We’re only showing one at a time now, so we don’t need to check whether
we have more than one.
> Don't check for multiple houses in term-table

- .travis.yml
- scripts/release.sh
We want to know if a release to viewer-static has failed, so we make it part of the build when we merge to master. This means the build will fail if the release script fails to push to viewer-static. I've also added an error message if wget exits with a non-zero code so it doesn't fail silently.
> Fail build on failed deploy

- app.rb
- views/front_index.erb
We no longer have our own countries.json file — it’s been replaced by the one stored in the everypolitican-data repo on Github. So link directly to that instead.
This should really be to rawgit.com instead, so people get the correct headers if they want to use it, but that'll happen in https://github.com/everypolitician/viewer-sinatra/issues/197
> Link to the countries.json file on Github

- app.rb
- lib/popolo_helper.rb
- t/web/term_table/australia.rb
- views/index.erb
(part of #291)
As long as you know the URL, you can now view either house of a bicameral legislature. 
Actually displaying the correct links to these comes as part of a separate change.
> Enable the display of either house

- app.rb
https://github.com/everypolitician/everypolitician-data/pull/316 introduced country[:name] and term[:slug]
Switch to using them, rather than replicating the logic here (and in all other similar apps)
> Use new countries.json values

- app.rb
- t/web/basic.rb
- views/country_missing.erb
When someone visits the page for a country that we don’t have data for yet, go to a page that explains that, rather than simply 404ing:
This lets the auto-complete search box not need to care whether a country exists or not — it can just send everything through.
https://github.com/everypolitician/everypolitician/issues/107 deals with ensuring that these pages get spidered for the static site.
https://github.com/everypolitician/viewer-sinatra/issues/360 deals with getting better text on that page.
> Add a "No Data Yet" page for a missing country

- app.rb
- views/about.erb
- views/contribute.erb
- views/new_index.erb
Split a Contributing page out of the About page, link to both from the new homepage, and hide the new search box until it’s ready to go live.
> Improve new homepage

- app.rb
- t/web/basic.rb
- views/country_missing.erb
Only go to the “no data for that country” page if it’s a country that’s actually in `world.json`.
And, because it’s in that list, we can now also show a name for it on the page.
> Better "missing country" pages

- t/web/term_table/seat_count.rb
- views/term_table.erb
The seat count table currently sums all Memberships held by that Party over the term, which is very misleading if people change parties a lot, of where Members get replaced (e.g. if they join the government)
Instead, only sum memberships which are/were unfinished.
Closes #393
> Only show current or final memberships in the Seat Count

- t/web/term_table/ni.rb
- views/term_table.erb
In the term table, don’t show the start date if if’s the same as that of the term, or the end date if it’s the same as the end.
Closes #400
> Only show relevant parts of membership dates

- views/term_table.erb
Some term pages were blowing up because we were checking if the end_date was `empty?`, without making sure it was a string first. 
This is because the CSV library ‘smartly’ converts short dates like ‘2004’ to integers, leaving long dates like ‘2004-01-01’ as strings. We should probably change that behaviour, but for now it’s simplest (and generally safer) to simply cast everything to a string before performing tests.
Closes #405
> Fix failing terms

- t/web/term_table/all_countries.rb
When we put the new homepage live (#385), the test that loads every country linked from it stopped doing anything, as none are now linked! Make that test fail if it can’t find any countries, but also now load from the correct place.
closes #408
> Make the "Load every country" test work again.

- lib/popolo_helper.rb
This gives them the correct content headers, etc. Fixes #197. Fixes #474
> Serve JSON and CSV from rawgit instead of githubusercontent

- views/sass/_components.scss
- views/sass/_custom.scss
- views/sass/_site-header.scss
Here's a before and after shot, of how a country page looks on a short (800px) but wide screen:
It compresses down even further for even shorter screens (below 600px high).
> Improve vertical spacing on short but wide screens

- scripts/release.sh
When the `release.sh` script runs after merging to master clone and run the politician-image-proxy scraper to update the images.
Fixes https://github.com/everypolitician/app-manager/issues/21
> Update politician-image-proxy when building viewer-static

- scripts/release.sh
Sometimes images temporarily error when scraping them only to work again
later. To try and improve this we scrape images every time there is a
viewer-sinatra build rather than just when a pull request is merged.
Fixes #519
> Update politician-image-proxy every travis build

- scripts/release.sh
Only scrape them when a push is done.
Fixes #531
> Don't scape politician images for pull requests

- app.rb
- views/layout.erb
- views/needed.erb
Add a page that lists which countries we need sources, or scrapers, for, based on Github tickets.
We create a static page, which will be rebuilt every time the site is regenerated, but that page then also uses jQuery to rebuild itself via the Github API, so that it's up-to-date when things change.
> What's needed

- views/all_countries.erb
The “what’s needed” page needs to be linked, so that the spidering
generates a static version of it.
> Add a link to the What's Needed page

- views/needed.erb
https://github.com/everypolitician/viewer-sinatra/commit/5751b72f41827edf86dfb07ff3b410b176b8be80 introduced conflict markers — get rid of them.
> Fixup: remove conflict markers

- views/country_selector.erb
- world.json
Sort the elements in the homepage dropdown list, to be friendlier in a non-JS environment (closes #587)
(And fix up a few more country aliases as a drive-by)
> Sort country names in dropdown list 

- world.json
Add better display names for both Congos on the homepage search box
> Better disambiguate Congo-Kinshasa and Congo-Brazzaville

- views/layout.erb
Setting images (or indeed anything) with `@request.base_url` doesn’t work, as at the time the
static site is generated, the base_url will `localhost`.
I manually pushed the image in https://github.com/everypolitician/viewer-static/commit/5f401e14476389586ad3d2905930e170581c1382
Fixes #669
> Make meta:image links absolute

- public/javascript/main.js
An onchange is fired as the field had focus, so don't redirect if we
don't have a selected entry.
> Stop Safari redirecting to localhost on page blur.

- app.rb
We added this in the hope that it would speed up building the site, but
(a) it didn't, as wget doesn't DTRT with it, and (b) we sped the build
up substantially in other ways anyway. All this does now is make so
that we have to do hard-refreshes when we change the layout (rather
than the data), so remove it.
> Remove the last_modified header

- views/data_structure.erb
- views/submitting.erb
Add links to the relevant Wikipedia pages when talking about parties/factions, and areas/districts.
> Link to Wikipedia pages on Parliamentary Groups and Electoral Districts

- app.rb
- lib/popolo_helper.rb
- public/javascript/main.js
- views/country_selector.erb
- views/homepage.erb
- views/sass/_custom.scss
Rather than hacking directly into the select-to-autocomplete module, we tweak the jQuery autocomplete settings *after* it has been instantiated on the page, supplying our own custom `_renderItem` method, which uses a list of people counts pulled in from the `title` attributes of the original select options.
Fixes #386 by showing people which countries have data and which don’t.
> Show politician counts in country autocomplete

- app.rb
- views/countries.erb
- views/country.erb
- views/sass/_custom.scss
- views/term_table.erb
Previously JSON download was presented alongside CSV download for a legislature’s membership table, despite the two files containing very different data.
This moves the JSON download link to the top of the term page (and names it clearly with the number of terms it contains) and also adds JSON download links to the country page.
@tmtmtmtm Before this can be merged, you need to pass the correct JSON file URL for each legislature into `country.erb` (in place of `@example_json_url`).
Fixes #370.
> Move JSON download button to avoid confusion over scope

- views/countries.erb
On the map, when someone clicks on a country in red, we now take them to
the /needed page
Closes https://github.com/everypolitician/viewer-sinatra/issues/772
> Link missing countries to the /needed page

- public/javascript/main.js
- views/sass/_custom.scss
Fixes a styling bug related to #769, where wide country names made the dropdown overflow the width of the search box above it.
Also, since menu items are more likely to wrap onto multiple lines now, we increase the line-height slightly to make them look better when they do wrap.
And for consistency, we use the same prototype-extending paradigm for the other autocomplete hack we added in 338648794956f315b7adca356caa8b6b99e7d792.
> Correctly limit width of homepage autocomplete dropdown

- public/javascript/main.js
- views/term_table.erb
By default we should order the names according the sort_name (where available — where it's not, it'll fall back on the `name` field).
<s>This has a slightly odd side-effect of meaning that once someone uses the clicky-arrows to re-sort, there's no way of returning to this order.  There may be a way of doing something with `restoreOriginalSortOrder` in the Javascript here, but it's not immediately obvious what that should be.</s>
This means that the behviour is:
* default: sort by sort-name (usually last name first)
* click on 'sort' in name field: sort alphabetically by display name (usually given name first)
* click on 'sort' in name field again: sort reverse alphabetically by display name
* click on 'sort' in name field again: return to sorted by sort-name
(With no way to reverse sort …
> Make sort_name the default sort

- views/data_structure.erb
Remove a paragraph that was accidentally duplicated. Fixes #189 (thanks @Gemmamysoc !)
> Remove duplicated paragraph

- public/javascript/main.js
- views/sass/_components.scss
- views/sass/_custom.scss
- views/sass/_houdini.scss
- views/sass/_mixins.scss
- views/sass/main.scss
- views/term_table.erb
We use the Houdini CSS library from other mySociety projects to handle the dropdown behaviour without JavaScript. But because Houdini uses `id/for` attributes we also needed to tweak the `$.fixedThead()` module to deduplicate ids on cloned elements.
Fixes everypolitician/everypolitician#324.
> Present CSV and JSON download options on term page

- views/term_table.erb
Fixes everypolitician/everypolitician#293.
> Simpler wording for earlier/later links on term page

- app.rb
- views/term_table.erb
Previously we were getting the person ids from the CSV and then mapping
those to the JSON. This changes that to instead get everything directly
from the popolo to avoid confusion where there are subtle differences
between the CSV and the JSON.
I tried to cherry-pick the appropriate commits but too much had changed to make it simple, so I just reimplemented on top of `master`.
Extracted from #5349
> Use Popolo JSON exclusively for the term table

- app.rb
Because we're getting the username out of the url some usernames contain
UTF-8 characters that need to be decoded before they are displayed.
Fixes https://github.com/everypolitician/everypolitician/issues/358
> Decode Facebook usernames before displaying on term page

- lib/popolo_helper.rb
- t/web/popolo_helper.rb
Rather than saying we've got 2.7m statements when we've only got 2.68m
we instead say we've got 2.6m. This means we won't claim we've got 2.7m
statements until we actually do.
Closes #5671
> Round down the number on the homepage

- app.rb
- t/web/term_table/party_groupings.rb
Don't show the list of Groups if there's only one entry (e.g. if
everyone is an Independent).
Closes https://github.com/everypolitician/viewer-sinatra/issues/5629
> Hide 'Party Groupings' section if only one group

- public/javascript/ep-card-filter.js
- public/javascript/main.js
Fixes #5407 by combining the previously separate `js-filter-input` and `[data-active-section]` handling into a single module.
State is saved to the URL hash, and new history entries are created as you filter, so you can bookmark or share pages as you see them, and can navigate backward and forward in history with your browser’s back/forward buttons.
> New comprehensive CardFilter class for showing/hiding cards on term page

- public/javascript/ep-card-filter.js
This wasn't working correctly due to a typo: `biography` instead of `bio` as the default section name.
Fixes https://github.com/everypolitician/everypolitician/issues/400
> Show biography section on person cards by default

- app.rb
- t/web/basic.rb
- t/web/term_table/australia.rb
- t/web/term_table/finland.rb
By default the title is just "EveryPolitican", so extend that for the
country and term pages to more accurately represent where we are.
Closes https://github.com/everypolitician/viewer-sinatra/issues/10130
> Add better `title` for pages

- views/countries.erb
Rather than being red, and taking you to the "Missing" page, make it
green and clickable through to the legislature.
Closes https://github.com/everypolitician/everypolitician/issues/430
> Make Northern Cyprus clickable on the map

- views/country.erb
- views/term_table.erb
can reintroduce them when I've sorted out not having wget record them as part
of the page name
(highlighting won't work on select terms for now)
closes #11631
> remove query params from the download links

- app.rb
- views/country.erb
- views/term_table.erb
This ensures GitHub Pages serves the file up as with an HTML content type.
closes #11634
> add .html suffix to download pages

- t/web/term_table/malaysia.rb
- views/layout.erb
- views/term_table.erb
If there is no country there will be no house name either, so I added a conditional under the title.
Wrapped it with an h3 tag.
It works for long names in country or house name.
Closes: #11915
> Add house name in the term table under country name

- views/sass/_custom.scss
- views/sass/_person-cards.scss
Fixes #10131.
The "headers" at the top of the term list section and the term members section now stack vertically on narrow screens.
> Improve term page layout on narrow screens

- public/javascript/main.js
- views/term_table.erb
Added tracking to interactive elements on term_table page: prev/next term links, term dropdown list, filter field, download button, section-toggles. 
Tracked elements are given the `data-ga-track-click` attribute.
Example: `<button data-ga-track-click='Download button'>…`
JS finds all elements with this attribute and attaches an event handler.
Closes #5420
> WIP Adding tracking to term-table page interactive elements

- Gemfile
We've been seeing various problems with getting this running, so let's
revert to pinning at 2.0.0
> Pin to ruby 2.0.0

- .rubocop.yml
- .travis.yml
Travis is having problems as it runs rubocop against vendor/, with lots of
failures.
By default this is excluded, but because we're supplying our own Exclude
list, that clobbers the defaults, so we need to put it back explicitly.
Whilst we're here, also switch to container-based builds.
> Make Travis happier

- README.md
Browserstack gives us free cross-browser / cross-device testing, in exchange for an acknowledgement in the README of projects for which we use it.
I just noticed, the EveryPolitician.org README is missing the acknowledgement.
> Thank browserstack in readme

- public/javascript/main.js
Just nudging javascript one notch inwards, within the jQuery "document ready" call.
Also made the minority places where there was 4-space indenting use 2-space to match the style in the rest of the file.
Tidying this up because I want to make changes in `main.js` (for #11911) and don't want to fix this up as part of that issue.
> tidy indenting of JavaScript in main.js

- .travis.yml
- Rakefile.rb
Running the entire test suite takes forever because it has to make sure
that every country works as a fully rendered page.
If we split those out to a separate `rake test:web` target, and ensure that
`rake test:all` runs all of them, then we can still run the full test suite
when needed, but the day-to-day run of the Page tests can be lightning
fast.
> Split the exhaustive web tests to a separate rake task

- app.rb
Rather than rolling our own logic for which type of page to display for
/country, depending on whether it's a country we have data for; know about
but have no data; or don't know about — simply let Sinatra take care of
those by supplying multiple routes.
This should help make https://github.com/everypolitician/viewer-sinatra/pull/14613 clearer and cleaner.
> Split out the separate routes to /country

- Gemfile
- Gemfile.lock
- lib/page/download.rb
Switch to the newest version of everypolitician-ruby where looking up a
missing country returns `nil` rather than throwing an exception.
A new rule of thumb also arises from this: keep logic out of `initialize` as much as possible.
> Upgrade to everypolitician-ruby 0.12

- lib/world.rb
- t/helpers/world.rb
We want to be able to plug a Country into the wrapper template so that
we can call `.name` and `.url` on it, without caring about whether it
originated from the `countries.json` or `world.json` files. So use a
Struct as a simple Adapter within the World class to allow us to call
these methods on the data from there.
> Let World return a suitable Country

- lib/page/home.rb
The app doesn't like us just 'require'-ing this directly. This is an
easy fix, but a little bit unsatisfying, not least because the tests
were passing without this, so it implies a deeper underlying problem
that we really need to address more generally.
> require_relative World

- .gitignore
- Gemfile
- Gemfile.lock
- app.rb
- lib/page/download.rb
- lib/page/home.rb
- t/page/download.rb
- t/page/home.rb
- t/test_helper.rb
This switches the existing page classes and their tests over to use `Everypolitician::Index`. It's currently pointing at the version of everypolitician-ruby in https://github.com/everypolitician/everypolitician-ruby/pull/44, so that will need to be changed back to `master` once that PR is merged.
> Switch to Everypolitician::Index

- .travis.yml
- Gemfile
As we’re moving to using named parameters everywhere, 2.0.0 isn’t really
good enough anymore — we want at least 2.1.0 so we get required parameters.
With libraries we want to stick to the oldest plausible version rather than
forcing users to upgrade their ruby, but with an app like this we can be a
lot more relaxed. So if we’re upgrading anyway, we may as well go to 2.3.1
> require ruby 2.3.1

- .rubocop.yml
- Gemfile
- Rakefile.rb
- app.rb
- config.ru
- lib/page/download.rb
- lib/page/home.rb
- lib/popolo_helper.rb
- lib/world.rb
- t/helpers/world.rb
- t/page/download.rb
- t/page/home.rb
- t/test_helper.rb
- t/web/basic.rb
- t/web/needed.rb
- t/web/popolo_helper.rb
- t/web/term_table/all_countries.rb
- t/web/term_table/australia.rb
- t/web/term_table/finland.rb
- t/web/term_table/malaysia.rb
- t/web/term_table/ni.rb
- t/web/term_table/nz.rb
- t/web/term_table/party_groupings.rb
- t/web/term_table/seat_count.rb
Now that we're on Ruby 2.3 Rubocop is suggesting that we use the new
'frozen_string_literal' everywhere, in preparation for 3.0. Helpfully,
`rubocop -a` even does it for us…
> Add "frozen_string_literal: true" everywhere

- app.rb
- lib/page/download.rb
- t/page/download.rb
Now that we're on ruby 2.3.1 we can be stricter about always requiring
named parameters to Page classes, and more flexible about how we say which
ones are required.
> named parameters everywhere

- app.rb
- lib/page/missing_country.rb
- t/page/missing_country.rb
- views/country_missing.erb
This PR extracts a missing country-page to be used by the :country route when information for a country is missing in everypolitician data.
The route was updated as well as the template that receives the `@page` instance from said route.
> Extract missing country page

- scripts/provision.sh
- scripts/release.sh
Split the viewer-sinatra build and deploy process into two functions and always call the build process. The deploy process is only called when we are on the master branch.
> separate release and build process

- app.rb
- lib/page/country.rb
- t/page/country.rb
- views/country.erb
- views/layout.erb
This pull request extracts the logic under the first `/:country/` route into a class `Country`.
* The relevant templates were updated to use the member fields of the class instance.
* The main layout template had to be updated since it was using `@page_title`, which we don't need to pass to the template as the `Country` class has its own `title` member. So now, if we pass a `@page` instance and the `title` is available, we use it. The `@page_title` is used to render the title of the page in the browser.
* Since we also don't have a `@country` when we are passing a `@page`, the same had to be done so that the main template layout uses the `country` field of the `@page` if it is available. The `@country` is used in the main layout template to render the heading of the page in the page's …
> Extract a Country page class

- views/countries.erb
Grouping the countries by the start letter is a little bit mind-bending
(and requires some duplication), so replace it with an explicit
`group_by`.
We should perhaps push more of this logic out into the Page, but this is
a quick win in the meantime.
> Simplify the countries loop

- app.rb
Rather than having each route create its own EveryPoltician::Index, set
it up once at the start.
We'll probably want to encapsulate this better later, but this is a
useful first step.
> DRY the live index

- app.rb
`wjson` and `WORLD` have now been successfully encapsulated in each of the `Page` classes which require them, so we can get rid of the global in `app.rb`
> remove unused WORLD

- Rakefile.rb
The files in t/web are nested more than one level deep, so we need to
use a double splat in the file list to pick them all up.
> Run all t/web test files in rake task

- app.rb
This means that the warnings don't get printed out when running the
tests.
> Use Sinatra's logger to print warnings

- app.rb
This is the only place left that uses this, so if we inline it here, we can avoid setting this up at boot time, and thus make https://github.com/everypolitician/viewer-sinatra/pull/14749/commits/8219fff60eefbbf31572b4ce1da0508f91c2bead simpler
> inline ALL_COUNTRIES into the term_table route

- lib/everypolitician_extensions.rb
- lib/page/home.rb
EveryPolitician::Country only has a person_count on a Legislature.
Let's pretend it also has one on a Country.
We might want to actually _add_ this to `everypolitician-ruby`, but
it's not totally clear year whether it's something that's generally
useful enough, so let's live with it here for a while first, and then
decide.
> Add a `person_count` to Everypolitician::Country

- app.rb
Rather than setting a ruby-level global to the Index derived from the
DATASOURCE file, use a proper Sinatra-level setting.
> Adding `index` to settings

- lib/world.rb
- t/helpers/world.rb
- t/web/term_table/finland.rb
- views/layout.erb
The `:url` member of the `Country` struct was renamed to `:slug` to play well with the real `Country` objects.
The main layout was calling a `:url` field in the `@country` returned by the currently displayed page, but `Country` objects don't have a url member, they have a `:slug` instead.
So by making the titles work for world countries, we broke it for EP countries.
After renaming `:url` to `:slug` in world countries, it should work for both types of country.
The main layout headings now call `@country[:slug]` instead of `@country[:url]`
so that both world-countries and EP-countries heading link to the right url.
Fixes #14816
> Fix header link

- views/countries.erb
Instead of calling keys on the hash, the template now uses the methods provided by the `Country` object.
> Use country methods in template

- lib/page/spider_base.rb
- lib/world.rb
- t/helpers/world.rb
- t/page/spider_base.rb
- t/web/spider_base.rb
- views/spider_base.erb
The `spider_base` template now uses the `countries` method instead of manipulating a JSON object.
> Fix the spider_base template

- app.rb
- lib/page/country.rb
- t/page/country.rb
If we instantiate a Country object with a slug for a country for which we don't have data, bad things ensue. Rather than making that the job of the Page object, have it require an already-instantiated (and thus valid) Country object, and make the route responsible for generating that. This approach should considerably simplify error handling everywhere and provide a cleaner separation of concerns.
Fixing up the template for this page will happen in another PR, as it's blocked by https://github.com/everypolitician/everypolitician-ruby/issues/46, and we can get this change through without waiting for that.
> pass Country object, not slug, to Country Page

- t/page/house_wikidata.rb
Extract the set up of the Pages out to helper functions, so that the
intent of each test is more clearly visible.
> rearrange the Wikidata page test

- Gemfile
- Gemfile.lock
- views/country_download.erb
Removing JSON references from download template
Removes all but one (house[:names] depends on new method implemented in EP Ruby (https://github.com/everypolitician/everypolitician-ruby/issues/49)).
> Remove JSON from download template

- lib/page/term_table.rb
- t/page/term_table.rb
When I started working on another template I realized that the term table class was using a lot of brackets as well instead of the methods, so I decided to make this change first before updating the term table template.
Things spotted but not fixed here, as they will require a bit more work, so maybe they must each have their own PR:
* in the Popolo::JSON instance, we are calling `popolo.popolo[:meta][:sources]`. Maybe we could add a method to that class to return these sources.
* in `current_term[:csv_url]`, this is something that was proposed but not added yet, there is an issue about it: https://github.com/everypolitician/everypolitician-ruby/issues/32 
* in `house[:popolo]` I guess it refers to the `popolo_url`, however, I think a new vcr cassete might be needed, as this happens at …
> Remove all brackets from the term page class

- Gemfile
- Gemfile.lock
This PR updates the version of the `everypolitician-ruby` gem so that it uses the last changes, in particular, the changes in the `csv_url` methods in the `Legislature` and `LegislativePeriod` classes.
> Update EP-ruby version to 0.17

- lib/page/term_table.rb
- t/page/term_table.rb
<s>Now that the EP-ruby has been updated to use the right `csv_url` coming from the data in terms, we can switch to calling the method instead of accessing the raw data through the hash key.</s>
The Term Table page no longer displays download links directly (these are now on the Download page), so we don't need a  `csv_url` method.
> Remove csv_url method from Page::TermTable

- lib/page/term_table.rb
- t/page/term_table.rb
The term-table page doesn't need to expose the popolo_url any longer
(as downloads happen from a separate page now), so we can kill off this
method.
> Remove `popolo_url` method

- lib/page/term_table.rb
There is no need to use the GitHubFile helper anymore to build the popolo url and file, since legislatures have popolo and popolo_url methods that can be used instead.
(cherry-picked from https://github.com/everypolitician/viewer-sinatra/pull/14954)
> Remove the GithubFile reference in the term table

- lib/everypolitician_extensions.rb
There is no need to use the `GitHubFile` helper anymore to build the popolo url and file, since legislatures have a `popolo` and `popolo_url` methods that can be used instead.
Also, since this class is not needed anymore, as EP-ruby and EP-popolo libraries already provide that functionality, this class is not used anywhere at this point.
This PR removes that class from the `CountryExtensions` helper and uses the proper methods from the EP-ruby legislature class.
> Remove githubfile class

- app.rb
- lib/page/download.rb
- t/page/download.rb
in keeping with how we're now constructing other Page objects, pass
through an actual Country object (`pass`-ing if we can't make one), not
just a slug.
> Download Page: pass a Country not a Slug

- Rakefile
- t/test_helper.rb
Following on from https://github.com/everypolitician/viewer-sinatra/pull/15129 this provides a handy rake task to run when you want to quickly download a missing fixture for `stub_everypolitician_data_request`.
> Add rake task for downloading missing everypolitician-data fixtures

- views/layout.erb
Replace all calls to `house[:name]`, `country[:slug]` etc to direct
method calls (`house.name`, `country.slug`)
> Remove indirect access in layout template

- lib/everypolitician_extensions.rb
- lib/page/term_table.rb
* Let a Term know its next/prev term
* Add LegislativePeriod.memberships
* Add LegislativePeriod.members_at_end
These let us pull more of the logic out of the TermTable Page, and onto the Term itself.
> Move methods from TermTable to Term

- lib/page/term_table.rb
- t/page/term_table.rb
the check should apply to the prior block (should we show email), not
the following one (should we show other contacts and identifiers)
Fixes https://github.com/everypolitician/viewer-sinatra/issues/15204
> fix incorrect nesting of email check

- lib/page/term_table.rb
- t/page/term_table.rb
- views/term_table.erb
By making the SeatCount a Struct, rather than plain Hash, we can
simplify the logic a little, take a small step towards extracting it
elsewhere, and remove some more direct hash lookups from the templates.
> Make SeatCount a struct

- t/page/house_wikidata.rb
- t/page/needed.rb
- t/page/term_table.rb
- t/test_helper.rb
- t/web/needed.rb
- t/web/term_table/australia.rb
- t/web/term_table/party_groupings.rb
- t/web/wikidata.rb
Factor out some more helper methods for test stubbing, and move the
setup closer to where it's used in each test case, so that the pattern
is easier to detect, and copy in other files.
> Simplify the test stubbing

- views/term_table.erb
Each of these is essentially doing the same thing, so wrap them up in a single loop.
This will avoid simple bugs (e.g. if we wanted to make one value a link in a different view), and will make it easier to vary the underlying implementation.
Everything still looks fine:
> Standardise card sections

- lib/page/term_table.rb
- t/page/term_table.rb
- views/term_table.erb
As part of the process of replacing all direct data-structure lookups with method calls on objects, create a lightweight Struct to represent the percentage data for each type of Card.
> Turn Percentages into a Struct

- lib/page/term_table.rb
- t/page/term_table.rb
- views/term_table.erb
Make the memberships on the Term Table page full Membership objects. To
do this we need to add `area` and `group` methods.
(`everypolitician-popolo` should really give us these, but until it does,
we need to construct them ourselves.)
> Pass full Membership objects to Term Table

- lib/popolo_helper.rb
The method on the Person Card provides this information directly, so we
don't need it in the helper.
> Remove image_proxy helper method

- app.rb
We found that there was not a consistent way of naming the slugs in the app routes so we renamed them to be less confusing and consistent.
For example some times there was `cslug`, some times `slug`, some times `country` (the latter was also confusing because there is a `country` that refers to the instance of a `Country` but was also refering to the slug), etc.
All the routes now have their slugs renamed to `country_slug` and `house_slug`.
> Rename route slugs for consistency

- lib/popolo_helper.rb
- views/country.erb
- views/country_download.erb
- views/term_table.erb
The `term_table_url` method in the popolo helper was simplify so that it is passed just a term, and the country and legislature are obtained from it using `term.country` and `term.legislature`.
I also changed the bracket notation and used the instance methods (`.slug` and `csv_url`) instead.
Finally, I updated the templates using it, **country.erb**, **country_download.erb** and **term_table.erb**.
Fixes #15241
> Simplify term_table_url

- app.rb
- lib/page/house.rb
- t/page/house.rb
- t/web/house.rb
- views/house.erb
This PR adds a new page class for a legislature.
* Adds a `Page::House` class and tests
* Adds the route to app.rb (`/:country/:house/`)
* Adds a new template and tests. The template was taken from the country template which was updated to show information from the house and to remove the loop on legislatures.
> House page

- views/house.erb
After rebasing master onto this branch and running the tests, some were failing due to the recent simplification of the signature of the term_table_url method. This commit updates the template to use the new signature.
>  Update to the new signature of term_table_url

- app.rb
- lib/page/house_download.rb
- t/page/house_download.rb
- t/web/house_download.rb
- views/house_download.erb
This PR creates dedicated download pages for a single-legislature-data download.
The per-country Download page is too cluttered and confusing, so we want to split it up into separate Download pages per legislature instead.
Part of #13599. Part of #15256.
Adds:
* A new page class, `HouseDownload`
* A route in the app.rb
* A new template (copy-pasted the country download one, removed the loop on legislatures and updated the relevant stuff to make it a legislature download page)
* Tests for what we send to the template from the new page
There is a lot of duplication here with the Country Download page (particularly the template). However, we will be removing that page before this one goes public, so it's OK to live with the duplication for a little while.
This should not go fully live (i.e. …
> Add "House Download" page

- t/web/basic.rb
- views/layout.erb
This PR addresses the point "_Ensure house/download links to House page_" in the mamma-issue #15256.
* It adds a test against the main layout to document the existence of a link to the house in house/download pages
* It adds a link to the house in the header of the main layout file.
It also corrects misalignment of the top variables in the layout template at the top
> Link to house in the headings of house/download.html

- Rakefile
- lib/everypolitician_extensions.rb
- t/everypolitician_extensions/membership_extension.rb
- t/fixtures/everypolitician-data/2b38667/data/Afghanistan/Wolesi_Jirga/ep-popolo-v1.0.json
Methods return group and area for a given member.
TermTable currently uses `#org_lookup` and `#area_lookup` to get the area and group for a given member. The intention is for the class to use the extension methods instead.
> Extend Popolo::Membership with #group and #area

- t/everypolitician_extensions/membership_extension.rb
Descriptions were named wrong. One was testing the area but described as testing the group and vice versa.
> Fix behaviour descriptions

- t/web/country.rb
- views/country.erb
In the Country view, make the download links in every legislature section point to their legislature-download dedicated page.
This PR depends on #15245 being merged
> Link to house/download

- app.rb
- t/web/redirect.rb
- views/redirect.erb
This PR supersedes [Country download redirect #15261](#15261)
This PR is the first part of splitting [Country download redirect #15261](#15261) in two. Second part here: #15466
It adds tests for the existing redirecting code (and which make the change at hand easy), leaving the second part of that PR as the part that can be the subsequent easy change.
[Country download redirect #15261](#15261) was a little too large, especially as it had a dependency on other PRs that weren't merged at the moment of its creation.
This is part of issue [release house and house/download pages #15256](#15256) regarding the post-live clean-up, and TO-DO list [TODO w/c 2016-08-30 #492](https://github.com/everypolitician/everypolitician/issues/492)
* Since the url of the host was hardcoded in the view, it is …
> Test redirect

- scripts/release.sh
This call to this function has been commented out for some time now.
The updates to the image proxy are happening as a cronjob on mySociety
servers currently, so this no longer needs to be handled as part of the
viewer-sinatra release process.
> Remove image proxy code from release.sh

- DATASOURCE
- README.md
- app.rb
- t/page/download.rb
- t/page/house_download.rb
- t/test_helper.rb
This changes viewer-sinatra to read the `DATASOURCE`, which is a url pointing to the `countries.json` file to use to get the data for the site, from an environment variable instead of a file.
As part of [changing the way everypolitician.org is deployed](https://github.com/everypolitician/everypolitician/projects/2) we want to be able to have a site builder gem that when invoked uses viewer-sinatra to build everypolitician.org using a specific version of `countries.json`. This pull request means that we can specify which version of `countries.json` we want to use without having to make a commit to viewer-sinatra.
Fixes https://github.com/everypolitician/everypolitician/issues/503
> Read DATASOURCE from an environment variable rather than a file

- .travis.yml
- scripts/release.sh
This changes the access token to be stored in a `.netrc` file rather than embedding them in the url. This should make it harder to accidentally leak the credentials. I've also reset the access token in `.travis.yml`, because it was accidentally leaked as part of a build.
> Use a .netrc for GitHub access token

- scripts/release.sh
When deploying the site we don't need to do a full ~700MB clone of
viewer-static as we're not using the history in the repository. This
should help speed up the deploy process a bit.
Related to https://github.com/everypolitician/everypolitician-data/pull/17407 where I made a similar change to that script.
> Do a shallow clone of viewer-static in release.sh

- app.rb
The comment was pointing to a shell task that was updated to be
splitted in two separate tasks, to build and deploy the static site,
in commit 0f36ab88bbd92437fb69c6094e03c4c41014c99e
> Update lower redirection comment in app.rb

- lib/page/term_table.rb
- lib/person_cards.rb
- t/page/term_table.rb
Currently we find the Top identifiers across a legislature, and then
include those for each person who has them. This commit changes
that behaviour to include up to 5 identifiers per person, ordered by
how common those are across that legislature.
I chose Harald for the tests because he has more than 5 identifiers.
Closes #6332
> Include top 5 identifiers per person

- t/test_helper.rb
- t/web/country.rb
- t/web/house.rb
- views/house.erb
- views/layout.erb
HTML-validates the house page and removes skip duplication
The HTML was broken and the skip was duplicated
https://github.com/everypolitician/everypolitician/issues/505
None
None
Errors corrected:
- An "img" element must have an "alt" attribute, except under certain
conditions. For details, consult guidance on providing text alternatives
for images. At line 254, column 69.
- End tag "div" seen, but there were open elements. At line 256, column 12.
- Unclosed element "a". At line 252, column 77.
None
> Use tidy-html5 to validate the house page

- t/web/house_download.rb
HTML-validates the house/download page
HTML could be broken, turns out it wasn't for this particular page, but the automated detection is now in place
https://github.com/everypolitician/everypolitician/issues/505
None
None
None
None
Errors corrected:
- No errors
> Use tidy-html5 to validate the house/download page

- views/term_table.erb
This updates the download button's URL on term tables to point to the house download page rather than the late country download page.  I changed the relative to an absolute URL 'cause octopusinvitro had done the same in #15255.
> Update download page URL on term table

- lib/page/term_table.rb
- t/page/term_table.rb
- views/term_table.erb
We currently have two conflicting places injecting methods into Membership objects for 'area' and 'group' — MembershipExtension, which returns the relevant objects of Area or Organization; and
`person_memberships` in the TermTable page, which then overrides these to be strings. This leads to all manner of odd and inconsistent behaviour.
Change this to use objects throughout by simply falling back on the version from the MembershipExtension.
(NB: This should also remove a *lot* of the test warnings, per https://github.com/everypolitician/viewer-sinatra/issues/15572)
> Return objects from membership.area and group

- t/test_helper.rb
This change adds a more robust check for a supported version of html-tidy.
Previously we were only checking that html-tidy was installed, however this meant that the user might have a very old version of html-tidy installed, which doesn't support HTML5. This new check now ensures that the user's version of html-tidy actually supports HTML5.
Closes https://github.com/everypolitician/viewer-sinatra/issues/15573
I've extracted the check for a supported version of html-tidy into it's own helper method to make it clearer what the check is actually doing.
> Check for supported version of html-tidy in tests

- t/web/countries.rb
HTML-validates the countries page
HTML could be broken, turns out it wasn't, but the detection is now in place
https://github.com/everypolitician/everypolitician/issues/505
None
None
Errors corrected:
- No errors
There was no test file for the countries page, so I created it from scratch.
> Use tidy-html5 to validate the countries page

- .travis.yml
This removes a duplicate `before_install` section from `.travis.yml` that I accidentally added in #15573.
Deploys of everypolitician.org were failing because I'd overwritten the `before_install` section that was adding credentials to `.netrc`, so git didn't have the correct credentials available to push to viewer-static.
#15573 was the pull request that introduced the problem.
> Remove duplicate before_install section in .travis.yml

- lib/page/house_download.rb
- t/page/house_download.rb
- t/web/house_download.rb
- views/house_download.erb
- views/sass/_components.scss
Links to other houses in the same country in the house/download page, because at the moment that section links to other countries only.
After merging the house/download page, it was clear that either a reword of the bottom of that page was needed (#15259) or either to go for the tab component integration directly (#15240). We changed our mind and went for the first one instead.
* Closes #15259 (Reword the house download page). 
* Last point in the first section of the workflow described in todo list #15256.
Adds:
* New method in the House/download page to check if there are other houses
* New method in the House/download page to get the other houses
* Tests to check that the link to other houses are displayed correctly and with the right information
* Updates the template.
At the moment …
> Link to other houses in the house/download page

- Gemfile.lock
- scripts/provision.sh
Installs Ruby 2.3.x as part of the Vagrant provisioning process.
The Gemfile required version 2.3.1 of Ruby.
–
–
–
–
–
> Vagrant provision.sh will now install Ruby 2.3.x

- public/javascript/ep-card-filter.js
- public/javascript/main.js
- views/sass/_components.scss
- views/sass/_custom.scss
- views/sass/_mixins.scss
- views/sass/_person-cards.scss
- views/sass/_typography.scss
- views/sass/_variables.scss
- views/term_table.erb
Fixes #6273 by introducing a new dropdown menu that you click to switch the visible "section" of each person-card (eg: bio, contacts, social).
Fixes #5408 by attaching the new filter bar to the top of the window when scrolling.
There's space to add a "Group:" dropdown (ie: a reworking of #5349) but I've left that to be done in a different PR.
Screenshots don't really do the scrolling awesomeness justice, but we can try:
(Sorry, arrows missing on the dropdown because Chrome device imitation is rubbish – they're there on the real devices)
All tested and working in all the major browsers. Degrades nicely in IE8.
> More obvious card filtering UI on term table pages

- Gemfile
Uses the `github:` shortcut in the `Gemfile` for gems that are not in Rubygems and we have to link to their repos.
For security reasons as described in http://bundler.io/git.html#security
Part of https://github.com/everypolitician/everypolitician/issues/518
* I ran `bundle exec rake bundle:audit` and got:
```bash
:) bundle exec rake bundle:audit
Updating ruby-advisory-db ...
De https://github.com/rubysec/ruby-advisory-db
* branch            master     -> FETCH_HEAD
Already up-to-date.
Updated ruby-advisory-db
ruby-advisory-db: 273 advisories
No vulnerabilities found
```
None
None
None
> Use the bundler github shortcut in Gemfile

- .travis.yml
- README.md
- Rakefile
It adds a new default task to Travis, so that running `bundle exec rake` runs everything and all the things: tests, syntax checks and security checks
Because it was easy to forget to manually run all the things before pushing, and get different results from Travis. Now we only have to run a single command.
"_Use default rake tasks to configure what runs on Travis_" https://github.com/everypolitician/everypolitician/issues/516
None
None
None
None
> Rake default

- app.rb
- lib/html_helper.rb
- lib/page/term_table.rb
- t/fixtures/everypolitician-data/4da60b8/data/Bahamas/House_of_Assembly/ep-popolo-v1.0.json
- t/web/term_table/bahamas.rb
- views/term_table.erb
Unescapes the URLs of the sources at the template level.
We were unescaping the URLs at the page level, so we were sending invalid urls to the template that we couldn't link to and were making the HTML validator complain.
Closes https://github.com/everypolitician/viewer-sinatra/issues/15583
A new helper file was added and the unescaping was moved from the term-table page to the term-table template, using the new helper.
It also adds a new fixture for the Bahamas which is an example of the urls this PR fixes.
Displayed urls
Linked urls
None
~~After this PR was published and reviewed, fixup commits were added that need auto-squashing before merging.~~
> Unescape URLs of Sources

- .travis.yml
Travis is currently timing out before completion.
https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received suggests this.
> Use 'travis_wait' to avoid timeouts

- Gemfile
- Gemfile.lock
This silences the "Warning: unrecognized cop Metrics/BlockLength found"
warnings
> Update to rubocop 0.46

- lib/page/term_table.rb
Depending on how the list of people to display on the term page is
generated, the displayed order of the people and the top identifiers may
be different. This is because before rendering the page, people are
sorted just on their sort_name attribute, and identifiers are sorted
by the number of identifiers of that scheme found in the term: if two
people have the same sort name (e.g. e.g. Octavio Jara Wolff and Sergio
Jara Catalán have the same sort_name, 'Jara') or if there are two
identifiers which occur the same number of times (often the case for
IDs schemes that occur only once or twice in a term) the items may
appear in different orders in the page between versions of the code even
though the same people with the same associated data are used for both.
This change makes the sorting of …
> Make the order of people and identifiers more stable

- Gemfile.lock
- lib/everypolitician_extensions.rb
- lib/page/term_table.rb
- lib/person_cards.rb
This pull request simplifies the dependencies of the `PersonCard` class,
so that it only needs to take a `Person` and a `LegislativePeriod` when
instantiating. It also moves some functionality from `TermTable` to
`LegislativePeriod` ~~(by monkey-patching the latter class).~~
In the future we would like to reuse these models in other projects, and
these changes make that reuse easier.
I couldn't find one, but some of these changes were suggested by "TODO"
comments in the existing source.
~~I'm not 100% sure if the monkey-patching of `LegislativePeriod` is sensible
or not - maybe similar changes in the original class in `everypolitician-ruby`
would be more useful in the long run, but I thought this was OK.~~
The appearance of the site should be unchanged by these.
I've run the recursive …
> Simplify the instantiation of PersonCard objects

- README.md
This adds a section to the README with details on the expected interface for using the unstable position data.
We want to add an interface for interacting with unstable position data to viewer-sinatra. This interface is an extension to the `EveryPolitician::Popolo::Person` class, which operates on the
`unstable/positions.csv` file in a legislature's directory in everypolitician-data.
Part of https://github.com/everypolitician/viewer-sinatra/issues/15606
- High level issue: Executive memberships https://github.com/everypolitician/viewer-sinatra/issues/24
I was originally going to add the `positions` method to the `Legislature`, but that doesn't really make sense, as it's people that hold positions, so that's where I've ended up putting the method.
In the (very near) future we'll be adding …
> Add README for unstable position data interface

- lib/page/term_table.rb
Adds YARD documentation for the `Page::TermTable` class.
This is part of the bigger effort to document all classes in this app (https://github.com/everypolitician/viewer-sinatra/issues/15310).
Part of https://github.com/everypolitician/viewer-sinatra/issues/15310
This change should make #15606 a bit easier to document.
> Add documentation for Page::TermTable class

- lib/person_cards.rb
Adds YARD documentation to the `PersonCard` class.
We want to document all the classes in this app as part of https://github.com/everypolitician/viewer-sinatra/issues/15310.
More specifically I want to properly document the new methods I'm adding for cabinet memberships, so documenting the rest of this class first means I'm not changing the whole world at once when adding docs for that.
Part of https://github.com/everypolitician/viewer-sinatra/issues/15310
Should make https://github.com/everypolitician/viewer-sinatra/issues/15606 easier to document…
> Add YARD documentation the PersonCard class

- t/page/term_table.rb
- t/test_helper.rb
- t/web/term_table/australia.rb
- t/web/term_table/bahamas.rb
- t/web/term_table/finland.rb
- t/web/term_table/malaysia.rb
- t/web/term_table/ni.rb
- t/web/term_table/nz.rb
- t/web/term_table/party_groupings.rb
- t/web/term_table/seat_count.rb
This adds an additional helper method to `test_helper.rb` called `stub_term_table`. As the name suggests it stubs out the requests that are made on the term table page.
As part of #24 we want to start making requests to `unstable/positions.csv` in the legislature directory of everypolitician-data. This means we'll be adding an additional HTTP requests to the term table page that need to be stubbed out. Having a single method where we can change what's stubbed for this page makes this much easier.
Extracted from https://github.com/everypolitician/viewer-sinatra/pull/15615
Related to https://github.com/everypolitician/viewer-sinatra/issues/15607
Part of #24
> Change term table stubbing in the tests

- .travis.yml
- scripts/check-fail.sh
This adds the `check-fail.sh` which runs tests added in pull requests and checks that they fail when run against the code on the `master` branch.
Having this script in place makes it much harder to add production code that doesn't have regression tests.
Part of https://github.com/everypolitician/everypolitician/issues/588
I've added the script last in `.travis.yml`, which means it will have to wait for the full viewer-static build to complete first. The reason for this is that `check-fail.sh` in its current form will alter the branch that the repo is on and won't put it back, so the `release.sh` script would have unexpected results if it ran after `check-fail.sh`.
> Add check-fail.sh

- lib/person_cards.rb
- t/page/term_table.rb
- views/term_table.erb
This renames `PersonCard#memberships` to `PersonCard#legislative_memberships`.
We want to add a `PersonCard#cabinet_memberships` method as part of #24. Therefore it makes sense to rename this method to `#legislative_memberships` to make it clear that it's only returning a subset of the memberships.
Extracted from https://github.com/everypolitician/viewer-sinatra/pull/15616
Part of #24
> Rename PersonCard#memberships to PersonCard#legislative_memberships

- README.md
- lib/person_cards.rb
- t/page/term_table.rb
Updates the documentation for the cabinet memberships methods that was added in https://github.com/everypolitician/viewer-sinatra/pull/15609 and moves it out of the README and into `lib/person_cards.rb`.
Originally we thought this code might be useful to outside people, as it was augmenting the everypolitician-ruby gem. Now though, we've decided that it's best for the functionality to live in some viewer-sinatra specific classes for now, until we have a better idea of how it all fits together at least. So this moves the docs to a more logical place.
Extracted from https://github.com/everypolitician/viewer-sinatra/pull/15615
Follows on from https://github.com/everypolitician/viewer-sinatra/pull/15609
Replaces https://github.com/everypolitician/viewer-sinatra/pull/15612
Part of #24 
This …
> Cabinet memberships documentation

- .travis.yml
- Gemfile
- Gemfile.lock
Updates the Ruby version to 2.3.3.
Most of our other apps and scrapers are running on Ruby 2.3.3, so this makes viewer-sinatra consistent with those. It also means we benefit from any fixes that are in the latest patch version.
> Update to Ruby 2.3.3

- README.md
- Rakefile
Renames the `test:all` rake task to be called `test`.
The `ensure-regression-tests` script that gets run on Travis assumes that all of your tests will run when `rake test` is executed. This wasn't the case for this repo, which means that the script was failing on Travis, even thought there were regression tests.
Fixes https://github.com/everypolitician/viewer-sinatra/issues/15625
> [Refactor] Rename rake test:all to test

- t/web/term_table/australia.rb
- views/term_table.erb
Adds an example snippet of Ruby (using the everypolitician gem) for accessing the data that's displayed on a term-table page.
Enhancement: if a potential developer is looking at that page on the EveryPolitician website, on the basis that a simple example is a dev's favourite favourite way of learning, then this communicates how easy it is to use the data in their own project.
#15611 
None: no design effort made here (e.g. syntax colouring, any dynamic hide/show etc)... this just uses an existing section style, with a new class (`page-section--code`) that has no explicit CSS associated with it — in fact this class is only used in order to isolate the code example the tests.
The output from running the snippet of code is non-specific: just `name (party): gender` which is enough to convey …
> Show Ruby code example on every term-table page

- Gemfile.lock
- scripts/install_tidy.sh
Gets Travis building `master` successfully again.
`master` cannot currently be built on Travis. We need successful builds to be able to continue to make changes.
N/A
Two problems were preventing the build from working.
Travis seems to now create a `~/bin` folder so the [`scripts/install_tidy.sh` script was failing](https://travis-ci.org/everypolitician/viewer-sinatra/builds/316179211#L796). 1500da4 fixes this by not failing if the directory already exists.
Two gems had new security advisories so [`rake bundle:audit` was failing](https://travis-ci.org/everypolitician/viewer-sinatra/builds/316180819#L960-L976). 87884b8 and 069ff9a fix this by updating the two gems.
N/A
N/A
N/A
> Fix Travis build

- t/page/term_table.rb
Some tests were causing this deprecation warning:
>DEPRECATED: Use assert_nil if expecting nil from $FILENAME. This will fail in Minitest 6.
This PR fixes those deprecation warnings by updating those tests to use `#must_be_nil` instead of `#must_equal nil`.
These warnings were added in [minitest 5.10.0](https://github.com/seattlerb/minitest/blob/master/History.rdoc#5100--2016-11-30) and we [upgraded to minitest > 5.10.0 recently](https://github.com/everypolitician/viewer-sinatra/pull/15633/files#diff-e79a60dc6b85309ae70a6ea8261eaf95L51).
Deprecation warnings on master: https://travis-ci.org/everypolitician/viewer-sinatra/builds/316216105#L896
Now no deprecation warnings: https://travis-ci.org/everypolitician/viewer-sinatra/builds/330669752#L1041
> Fix test deprecation warnings about not using assert_nil

- Rakefile
Explicitly suppresses warnings when running the full test suite.
Prior to Rake 11.0 Rake::TestTask warnings were disabled by default but
now they're enabled.
https://github.com/ruby/rake/blob/master/History.rdoc#1100--2016-03-09
>Use ruby warnings by default. Pull request # 97 by Harold Giménez
We upgraded to Rake > 11.0 in:
https://github.com/everypolitician/viewer-sinatra/pull/15633/files#diff-e79a60dc6b85309ae70a6ea8261eaf95R77
Now that they're enabled we need to explicitly disable them on our test
task that runs the full test suite. This is because we don't yet have
the test suite running cleanly without warnings, though we do want to
(see https://github.com/everypolitician/viewer-sinatra/issues/15572).
Test output before PR: …
> Suppress warnings when running the full test suite

- lib/everypolitician_extensions.rb
This returns a list of all other known identifiers for the people in
this term, and in turn lets us simplify the `top_identifiers` method
(dropping its flog score from 28.4 to 16.9).
> Add an identifier_map method

- .travis.yml
- Gemfile
- Gemfile.lock
- README.md
- scripts/provision.sh
Enables you to run `vagrant up` in the project directory, and be given a working vagrant VM, so you can `vagrant ssh` in and run `foreman start` to work on the EveryPolitician front-end locally.
The Vagrant provisioner was out of date from #15649  – it requested a version of Ruby that caused an error from Bundler, and it lacked a bunch of native packages that `capybara-webkit` requires.
Tested with Vagrant 2.0.2 and Virtualbox 5.2.8r121009 on macOS 10.13.3.
> Vagrant ruby capybara updates

- CONTRIBUTING.md
Add information about our use of `reek` as well as `rubocop`, and make it a little clearer that travis also requires new tests (unless a branch has "refactor" in the name)
> Note project's use of reek and ensure-regression-tests in CONTRIBUTING
