everypolitician/viewer-sinatra

app.rb
lib/popolo_helper.rb
t/helpers/eduskunta.rb

Move to Class based approach for JSON file, so we can handle more than one file.

Explicit Datafile

---

README.md
app.rb
views/sass/_components.scss
views/sass/_layouts.scss
views/sass/_mixins.scss
views/sass/_site-footer.scss
views/sass/_typography.scss
views/styling.erb

Fixes #8. 
I've refactored lots of the Sass, added a "Style guide" for non-designers, and added a Readme telling people about Vagrant, Sass, and the new style guide.

Style guide

---

views/parties.erb
views/terms.erb

- fa-university is now used for Terms
- fa-users for Parties
fixes #17

Change icons for Terms and Parties

---

app.rb
lib/popolo_helper.rb
t/helpers/eduskunta.rb
views/area.erb
views/person.erb

View an Area by Name.
Ideally we'd want to be able to handle by ID etc too, but for now this will work for the sorts of files we're getting from the CSV converter which just generate a bare `{ name : X }` record in-place on the Membership.

Add a simple Area page

---

views/term.erb

Give the list of people on a term page the same styling
as the list on the people page.
Fixes #33.

Style the list of people on a term page.

---

lib/popolo_helper.rb
t/helpers/eduskunta.rb

This won’t cope with lots of cases, but it’s enough to be getting on
with…

Add a (basic) current_term method

---

app.rb
data/greenland.json
lib/popolo_helper.rb
t/web/greenland.rb

Add data for Greenland (generated at https://github.com/tmtmtmtm/greenland-inatsisartut)

Add data for Greenland

---

data/greenland.json
data/greenland/Rakefile.rb
data/greenland/greenland.json
data/greenland/popit.json
views/term.erb
views/terms.erb

We’ll probably want to move this to a separate data repo, but let’s evolve towards that as we go.

Rakefile for re-generating the Greenland data

---

t/web/eduskunta.rb
views/term.erb

Group the people on a Term page by their Party:
Closes #73 
Closes #46

Group by Party on Term page

---

data/za/Rakefile.rb

Add a Rakefile to process the ZA Popit. It’s still not ready to actually *use*, but pushing anyway, as it’s still an improvement.

Improve ZA data

---

.travis.yml

Update Travis for Slack notifications

---

app.rb
lib/popolo_helper.rb
t/web/term_table.rb
views/front_index.erb
views/index.erb
views/layout.erb

Make everything work as standalone static pages that can be fetched with a wget.
Closes #100

Static Pages

---

app.rb
data/denmark.json

Data from https://github.com/mysociety/everypolitician-data/pull/1

Add Denmark

---

app.rb
data/estonia.json

From https://github.com/mysociety/everypolitician-data/pull/2

Add data for Estonia

---

public/javascript/main.js
views/sass/_components.scss
views/styling.erb
views/term_table.erb

For #96.
Add a class to a table, and it becomes sortable!
Works with [fixed headers](https://github.com/mysociety/popolo-viewer-sinatra/commit/472768fa5acb06b9c3b983d63a07ded428f87505) too.

Sortable table plugin

---

data/chile.json
t/web/chile.rb

Rather than 'current', use the actual data.

Change the Term information Chile

---

app.rb
t/data/term_table.rb

Add a CSV download route (not linked up yet)

Add route for download as CSV

---

app.rb

there’s probably a way to get this from within the template, but rather than having to construct it there, just pass it in.

Pass CSV url to Template

---

views/sass/_components.scss
views/sass/_custom.scss
views/sass/_variables.scss
views/term_table.erb

Closes #99.
Part of #96 
@tmtmtmtm: Once you've got CSV downloads working, you can point this button at the download endpoint, and merge this branch.

Non-functional download button on term_table.html

---

app.rb
t/web/basic.rb
t/web/term_table.rb
views/layout.erb

Set a `@page_title` for the term table

---

app.rb

Display the Turkish data added from EveryPolitician

Add viewer for Turkey

---

data/botswana.json
t/web/term_table.rb
views/term_table.erb

Add Botswana

---

app.rb
data/UK.json
lib/popolo_helper.rb
views/front_index.erb
views/index.erb
views/layout.erb
views/term_table.erb

and change how country names display, so the UK isn’t “Uk”

Add new 2015 UK data

---

app.rb
lib/popolo_helper.rb
t/web/term_table.rb
views/term_table.erb

Link to the SOURCE set in the data.
Closes #161

Display source information

---

public/data/Brazil.json

Add initial data for Brazil

---

app.rb
t/data/countries_json.rb

For now just listing the Country names and the URL they appear at

Add a countries.json

---

app.rb
lib/popolo_helper.rb
public/data/Wales.json
t/data/term_table.rb
t/helpers/wales.rb

And link to the current_term_csv in the countries.json

Add email and twitter handles to term CSV

---

public/data/Australia.json
t/web/term_table.rb

From a new source, so we need to update the test too.

Australia: refresh data

---

public/data/Northern_Ireland.json

Add data for Northern Ireland

---

public/data/Niger.json

Niger: initial data

---

public/data/Tanzania.json

Tanzania: initial data

---

lib/popolo_helper.rb
t/data/term_table.rb

https://github.com/everypolitician/everypolitician-data/issues/95 will
ensure that the details exist in both places, but until then we should
check each of them.
Closes #196

Get Twitter details from contact_details or links

---

Gemfile
Vagrantfile
app.rb
lib/popolo_helper.rb
t/data/countries_json.rb
t/data/term_table.rb
t/helpers/eduskunta.rb
t/helpers/wales.rb
t/web/basic.rb
t/web/chile.rb
t/web/eduskunta.rb
t/web/greenland.rb
t/web/term_table.rb
t/web/wales.rb

Various fixups to make Rubocop happier.

Rubocop Fixups

---

app.rb
views/index.erb

This isn't link to from anywhere yet, so won't appear on the static version of the site. #225 will change that.

Add an index page for each country

---

lib/popolo_helper.rb
t/data/countries_json.rb

Rather than serving up our own version of Popolo, link directly to the
version on raw.githubusercontent.com

Link directly to the githubusercontent CDN for Popolo

---

views/front_index.erb
views/index.erb

From the list of countries, link to the front page for the country,
rather than its latest term.

Link to a country's home page rather than latest term

---

lib/popolo_helper.rb

The previous version is very slow on large datasets. This works better for now.

Improve `terms_with_members`

---

app.rb
lib/popolo_helper.rb
t/helpers/eduskunta.rb
t/web/term_table.rb
views/index.erb
views/term_table.erb

Instead of calculating what terms we have, just use the list supplied
in countries.json

Use countries.json more

---

DATASOURCE
app.rb
lib/popolo_helper.rb
views/index.erb
views/term_table.erb

Cope with the new `countries.json` file layout from https://github.com/everypolitician/everypolitician-data/pull/258
(For now we just assume a single legislature per country — we still need to cope with more)

New countries file layout

---

DATASOURCE

@chrismytton — any idea why this didn't auto-deploy from https://github.com/everypolitician/everypolitician-data/pull/290?

Add Cameroon

---

app.rb
t/web/term_table/australia.rb
views/term_table.erb

Rather than generating the term-table pages from the Popolo JSON, generate them from the CSV file for that term. 
This will be a lot faster, and also show up any problems with the generation of those files.

Use the CSV files for the Term Table

---

t/web/term_table/australia.rb
views/index.erb

If there is more than one house or legislature, link to the term list for each.

List each house separately

---

app.rb
views/about.erb

With placeholder text from the static version of the site.
(Not linked to yet)

Add an about page

---

app.rb
views/front_index.erb
views/new_layout.erb

Once we put the new homepage (#303) live, we'll no longer have the map that's on the existing jekyll homepage. So let's pre-emptively add it to the big list-of-countries page. 
Closes #170

Add the map to the Data page

---

views/layout.erb

Closes https://github.com/everypolitician/everypolitician/issues/91

Add Google Analytics code

---

public/javascript/main.js

Take user to country on homepage selection

---

world.json

Add some places we have (or may have) that didn’t appear in the source
list of countries we used to build `world.json`

Add some missing countries to world.json

---

app.rb
views/about.erb
views/contribute.erb
views/technical.erb

Broadly these are the words from shared google doc with some (still) outstanding comments not quite addressed. This is being precipitated by me going on leave, sorry :-1:

About pages

---

app.rb
scripts/release.sh
views/all_countries.erb

This isn’t linked to from anywhere, but can be spidered by the process that builds the static site, so as to ensure we get the “No data” page for the countries we don’t have yet.

Add a page that lists every country we hope to have

---

views/layout.erb

This ensures it’ll be correctly mirrored to the static site.
Closes https://github.com/everypolitician/everypolitician/issues/121

Add a link to the favicon to the header

---

views/layout.erb

The favicon should have be to `/favicon.ico` not to `favicon.ico`!

Make the favicon link relative

---

views/about.erb
views/contribute.erb
views/country.erb
views/country_missing.erb
views/homepage.erb
views/layout.erb

Lots of textual changes throughout the site. 
Closes #337. Close #308.

Text changes

---

views/term_table.erb

Tell people what to do if the data on the term table is wrong, or
incomplete.
Closes #130

Add 'contributing' link to term table footer

---

world.json

For some reason it wasn’t listed, so can’t be searched for.
Closes #435

Add Niue to world.json

---

app.rb
views/data_structure.erb
views/repo_structure.erb
views/technical.erb

Add a better explanation of what we do and don't provide. (from a draft by @davewhiteland)

Better documentation

---

views/data_structure.erb

Improvements from @MyfanwyNixon

Improved documentation

---

app.rb
views/contribute.erb
views/data_structure.erb
views/submitting.erb

Add a page on our preferred data submission format.

'Submitting' page

---

app.rb
views/homepage.erb

Add a count to the homepage for how many people we have.
This might make the line too long. @zarino, you think this looks OK like this, or should we do something different?
Closes #429

Display number of politicians

---

views/about.erb
views/about_nav_menu.erb
views/contribute.erb
views/data_structure.erb
views/repo_structure.erb
views/sass/_components.scss
views/submitting.erb
views/technical.erb

this has added a couple of column-wrangling divs to each of the docs pages, which has changed the indenting on the body of the texts, but I don't think there are material changes in the words :-)

Add nav to docs

---

world.json

Make searching for “Aland” do the right thing.
Closes https://github.com/everypolitician/everypolitician/issues/122

Add Aland as alias for Åland

---

views/needed.erb

Making a PR so @tmtmtmtm can quickly check on the automagic staging site for approval on needed.html

add description of finding source, closes #578

---

views/about.erb
views/contribute.erb
views/repo_structure.erb
views/sass/_custom.scss
views/scrapers.erb
views/submitting.erb
views/technical.erb

New .section-intro style, to solve p.lead overloading

---

app.rb
views/needed.erb

Show the countries that someone is currently working on.

Add an "In Progress" section to the Needed page

---

views/needed.erb

Rebuild the “In Progress” list in JS as per the other two.

Dynamically adjust the "in Progress" list

---

scripts/release.sh

Refs https://github.com/everypolitician/viewer-sinatra/pull/620#issuecomment-139165313

Stop Travis always failing for external PRs

---

views/glow_banner.erb

Hat tip to @MyfanwyNixon for specific wording.
(this isn't chutzpah; we know country numbers 200 and 201 are
*almost* done...)

changed wording in anticipation of hitting GLOW target

---

app.rb
views/term_table.erb

Show unescaped data source as link text.

---

t/web/needed.rb
world.json

Make sure that all countries we have, and all countries we want, are represented in world.son
Closes https://github.com/everypolitician/viewer-sinatra/issues/499

Ensure world.json is complete

---

app.rb
views/countries.erb
world.json

Following @zarino's excellent suggestion at https://github.com/everypolitician/viewer-sinatra/pull/770#issuecomment-146951728, say how many countries we're still missing, and link to the page where we explain how people can help.
Closes https://github.com/everypolitician/viewer-sinatra/issues/773

Link to /missing from countries page

---

app.rb
views/all_countries.erb
views/fourohfour.erb
views/sass/_custom.scss

404.html page for Github Pages to display

---

app.rb
lib/popolo_helper.rb
views/wikidata_match.erb

Partition the list of all members of this legislature based on whether
or not we have a Wikidata match. This page isn’t linked from anywhere,
so won’t be mirrored to the static site.

Simple page to view Wikidata matches

---

views/submitting.erb

'source' is a required field on submitted data

---

views/countries.erb
views/homepage.erb

The map doesn't do well with country codes that aren't in upper case, so force everything up. Closes
https://github.com/everypolitician/viewer-sinatra/issues/935

Force country codes to upper case

---

views/submitting.erb

For @tmtmtmtm to check please!
closes #963

describe use of identifier__ ids in import

---

app.rb
views/about_nav_menu.erb
views/data_summary.erb

new page answering most common question (imo) from MozFest; closes #948

new page to summarise data available

---

views/sass/_components.scss
views/term_table.erb

The static site isn't building because of failing URLs
Fix the ones from the CSS, and from broken facebook relative links.

Term table fixups

---

views/term_table.erb

For now, let's keep this to links to other sites, whilst we work out
what exactly this should be.

Don't display email addresses

---

app.rb
views/term_table.erb

Fixes #5265.
Eg: /transnistria/supreme-council/term-table/6.html

Hide Party Groupings section if there is only one party and it is “Unknown”

---

views/term_table.erb

Rename 'biography' to 'biographical'

---

app.rb
lib/popolo_helper.rb
views/homepage.erb
views/sass/_custom.scss

This is the first part of https://github.com/everypolitician/viewer-sinatra/pull/5351.

Show number of claims on homepage

---

views/sass/_person-cards.scss
views/term_table.erb

Suggest examples of what to search for in js-filter-input

---

views/sass/_person-cards.scss
views/term_table.erb

Fixes #6274.
**Before:**
**After:**

Use tables inside person cards to avoid key/value overlaps

---

views/sass/_layouts.scss
views/styling.erb

closes #10619 
For @zarino to sanity-check please

tweaked so column widths sum to < 100%

---

views/layout.erb

Tweak the recently added UTM tag in the footer, to match our new standard: https://wiki.mysociety.org/wiki/Google_Analytics#Custom_Campaigns

Standardise footer UTM tracking with other sites

---

Gemfile.lock
app.rb
t/web/term_table/australia.rb

Added honorific titles to p[:bio] in app.rb
Updated gems.

Issue 5624 bio card honorifics c

---

Rakefile.rb
lib/page/home.rb
lib/world.rb
t/helpers/world.rb

Rather than have individual Page classes interact directly with `world.json`, encapsulate it in a basic class.  This can get more advanced later (ideally being harmonised with `countries.json`), but for now just use it to return the raw JSON.

Add a simple World class

---

app.rb
lib/page/house_wikidata.rb
lib/popolo_helper.rb
t/page/house_wikidata.rb
views/wikidata_match.erb

Extracted logic from `/:country/:house/wikidata` to new class.
Referenced new class in app.rb and era

Extract house wikidata class

---

app.rb
lib/page/countries.rb
t/page/countries.rb
views/countries.erb

This PR extracts a countries page class from the app route.

Extract a countries page class

---

lib/page/countries.rb
t/page/countries.rb
views/countries.erb

Remove logic from the template where it doesn't belong, and pull it back up
into the Page class.

Add a `missing_countries` method in Page::Countries

---

app.rb
lib/page/needed.rb
t/fixtures/vcr_cassettes/test_0002_should_know_that_Eritrea_is_missing.yml
t/fixtures/vcr_cassettes/test_0003_should_currently_have_nothing_to_scrape.yml
t/fixtures/vcr_cassettes/test_0003_should_have_popolo_with_wikidata.yml
t/fixtures/vcr_cassettes/test_0004_should_currently_have_nothing_to_finish.yml
t/page/needed.rb
views/needed.erb

Extracted logic in /needed to new class. 
Added VCR and made it work only for requests made in tests for this class. (Requests made to DATASOURCE url ''https://cdn.rawgit.com/everypolitician/everypolitician-data...' are not wrapped in VCR.use_cassette blocks.)
Referenced new class in app.rb and erb.

Extract needed page

---

app.rb

Set most of these up dynamically, and move the helper function to the
bottom of the file where it doesn't interrupt the flow so much.

tidy the 'redirect to docs' section

---

lib/everypolitician_extensions.rb
lib/page/countries.rb
lib/page/country.rb
lib/page/download.rb
lib/page/home.rb
lib/page/house_wikidata.rb
lib/page/term_table.rb
lib/popolo_helper.rb

Clean up the `require` block in each Page to only be requiring things that
are actually needed by the class.

remove unnecessary `require`s

---

lib/page/countries.rb
lib/page/country.rb
lib/page/download.rb
lib/page/home.rb
lib/page/house_wikidata.rb
lib/page/missing_country.rb
lib/page/needed.rb
lib/page/spider_base.rb
lib/page/term_table.rb
t/page/home.rb
t/page/house_wikidata.rb
views/layout.erb

Make sure that every Page has a title, so we can always call `page.title` in 
the layout.

Ensure every page has a Title

---

views/homepage.erb

The homepage template now uses country methods.

Fix the homepage template

---

app.rb
lib/page/house_wikidata.rb
t/page/house_wikidata.rb

similarly to https://github.com/everypolitician/viewer-sinatra/pull/14877, make the route pre-check validity, and pass an instantiated Legislature to the Page

Make Wikidata route responsible for Legislature

---

Gemfile
Gemfile.lock
t/web/country.rb
views/country.erb

Replace all []-based accesses in the country template with method calls.

No [] access in country template

---

lib/page/needed.rb
t/page/needed.rb
views/needed.erb

Needed template now works with objects

Replace references by key with method calls

---

lib/page/term_table.rb

We don't need iterate through the houses, checking by slug: there’s a method that will give us that directly!

Use a country method to obtain the house

---

lib/page/home.rb
lib/world.rb
t/page/home.rb
t/web/homepage.rb
views/country_selector.erb
views/homepage.erb

if `World` is given an `EveryPolitician::Index`, map each `World::Country` to its connected `EveryPolitician::Country`, and use this combination for the Homepage.
(This is starting to stretch the Struct a little far, so we probably want to look into extracting a proper class for that RSN.)

include EveryPolitician::Country into World::Country

---

Gemfile
Gemfile.lock
t/web/download.rb
views/country_download.erb

Adds `house.csv_url` to template. Removes house[:names].

Add house.csv_url to download template

---

views/term_table.erb

This reduces the number of direct calls from 61 to 49.

Remove indirect access in term_table template

---

app.rb
lib/everypolitician_extensions.rb
lib/page/term_table.rb
t/page/term_table.rb

Rather than constructing this with four(!) arguments, all it really
needs a Term object, from which it can, in turn, get its House and
Country. (And won't need an Index at all)

Construct the TermTable page with only a Term

---

lib/page/term_table.rb

first step towards better handling of the data cards for a person on the TermTable page — simply pull the data for each card out into its own method. No other tidying has been applied yet — that can happen in future changes.

Factor data cards into separate methods

---

lib/page/term_table.rb

This still needs more work, but it drops this from being the method
with the highest flog score (69.8) to sixth place (24.1)

factor out repeated code in `percentages`

---

lib/page/term_table.rb
lib/person_cards.rb

Take each of the methods to generate a view on the Person data (e.g. the `bio` 
section), and extract them as individual classes.
At this point we don't try doing anything more complex than transposing the body of the method into a simple `data` method on the new class.
Everything still looks fine afterwards:

extract PersonCards

---

t/page/term_table.rb

rather than comparing to one big complex data structure, test each
component in turn, so we can see more clearly where any problems lie if
they differ.

Split up the term_table Card test

---

lib/page/term_table.rb
lib/person_cards.rb
views/term_table.erb

Turn the data into structs, so we can call methods on them rather than using raw data.

Switch to using CardLine objects for the Person cards

---

lib/page/term_table.rb
lib/person_cards.rb
t/page/term_table.rb
views/term_table.erb

This includes the higher level details for the person, plus all the individual Sections.

Make a holding PersonCard

---

.github/ISSUE_TEMPLATE.md

Actually this is a standard issue template copied over from another EveryPolitician repo
Over to @tmtmtmtm, thanks

new issue template for viewer-sinatra

---

t/fixtures/everypolitician-data/bd08b5e/data/North_Korea/National_Assembly/ep-popolo-v1.0.json
t/page/term_table.rb

#group_data should return an empty array when there is only a single group for a given term. Added test to test that.

Test group_data for empty array

---

.gitignore
Gemfile
Gemfile.lock
lib/page/home.rb

Add YARD, and add some initial documentation of a single class (Page::Home). 
There are undoubtedly lots of ways to improve on this, but this is initially just seeing how the basic approach works before rolling it out everywhere.

First steps towards documentation

---

t/page/term_table.rb

We already have a section for these, so no need to ram them all in
together.

Split up the group_date tests

---

README.md

After some while not working in this repo, I came back to it and couldn't remember how to run the tests. Hopefully I remembered that it was all documented in the relevant rake file. But not in the README. So this PR documents it there as well.

Document all the ways to run tests in the README

---

scripts/release.sh

These two scripts are very similar, so they now link to each other so
that any changes can be either kept in sync or possibly refactored into
a shared library at some point.
Related to https://github.com/everypolitician/everypolitician-data/pull/17407

Link to everypolitician-data's deploy script from release.sh

---

.travis.yml
Gemfile
Gemfile.lock
scripts/install_tidy.sh
t/test_helper.rb
t/web/country.rb
views/country.erb
views/layout.erb

Adds tidy-html5 as an HTML validator and fixes the country page.
Because we didn't have a way to automatically detect, say, a missing `</a>`.
https://github.com/everypolitician/everypolitician/issues/505
A script was added to install tidy in Travis
None
This is the first of many PRs to come!
None

Fix closing tag 1

---

t/web/needed.rb
views/needed.erb

Don't show these sections unless there are any countries in them.
Closes https://github.com/everypolitician/viewer-sinatra/issues/15596

Don't show sections with no countries

---

CONTRIBUTING.md
README.md

Set out the basic code-level approach used in this project, with an
explanation of how we like to receive PRs.
This is an initial version, cobbled together almost entirely from notes
from previous discussions and reviews, to ensure we capture these
somewhere public. This is expected to evolve (probably quite heavily)
over time.

Add a 'CONTRIBUTING.md'

---

views/country.erb
views/house.erb
views/sass/_custom.scss
views/survey.erb
views/term_table.erb

The survey added in https://github.com/everypolitician/viewer-sinatra/pull/15590 has served its purpose.
The current priority is the Wikidata integration.

Remove the survey

---

Gemfile
Gemfile.lock
README.md
app.rb

[Reopening of #15635 to include `refactor` in branch name to make `ensure-regression-tests` happy.]
This reloads files that have been changed in development. 
It's useful for us when app.rb has been changed because prior to this you needed to
manually restart the server if you changed this file.
N/A
N/A
N/A
Includes `refactor` in branch name so `ensure-regression-tests` passes. Since this is only introducing functionality in development we don't expect there to be new tests that fail against master.
N/A

Install sinatra reloader

---

README.md

Remove a spurious space that has crept in.

Remove needless space from README

---

.rubocop.yml
.travis.yml
Gemfile
Gemfile.lock

We updated the data repo to use 2.4 in
everypolitician/everypolitician-data#135293
Bring this in line

Update to ruby 2.4.4

---

views/layout.erb

Remove cookie tracking from GA
We don't want to track individual users
https://github.com/mysociety/orgsites/issues/1124
Could you merge and deploy this if it looks ok and it's reasonably easy, and let me know if it's not easy? Thanks!

Remove cookie storage from GA
